const express = require("express")
const app = express()
const PORT = process.env.PORT || 3000

const data = {
	i: {
		name: "Tarapacá",
		communes: [
			"Alto Hospicio",
			"Iquique",
			"Camiña",
			"Colchane",
			"Huara",
			"Pica",
			"Pozo Almonte",
		],
	},
	ii: {
		name: "Antofagasta",
		communes: [
			"Antofagasta",
			"Mejillones",
			"Sierra Gorda",
			"Taltal",
			"Calama",
			"Ollagüe",
			"San Pedro de Atacama",
			"María Elena",
			"Tocopilla",
		],
	},
	iii: {
		name: "Atacama",
		communes: [
			"Chañaral",
			"Diego de Almagro",
			"Caldera",
			"Copiapó",
			"Tierra Amarilla",
			"Alto del Carmen",
			"Freirina",
			"Huasco",
			"Vallenar",
		],
	},
	iv: {
		name: "Coquimbo",
		communes: [
			"Andacollo",
			"Coquimbo",
			"La Higuera",
			"La Serena",
			"Paihuano",
			"Vicuña",
			"Combarbalá",
			"Monte Patria",
			"Ovalle",
			"Punitaqui",
			"Río Hurtado",
			"Canela",
			"Illapel",
			"Los Vilos",
			"Salamanca",
		],
	},
	v: {
		name: "Valparaíso",
		communes: [
			"Rapa Nui",
			"Calle Larga",
			"Los Andes",
			"Rinconada",
			"San Esteban",
			"Cabildo",
			"La Ligua",
			"Papudo",
			"Petorca",
			"Zapallar",
			"Hijuelas",
			"La Calera",
			"La Cruz",
			"Nogales",
			"Quillota",
			"Algarrobo",
			"Cartagena",
			"El Quisco",
			"El Tabo",
			"San Antonio",
			"Santo Domingo",
			"Catemu",
			"Llai-Llay",
			"Panquehue",
			"Putaendo",
			"San Felipe",
			"Santa María",
			"Casablanca",
			"Concón",
			"Juan Fernández",
			"Puchuncaví",
			"Quintero",
			"Valparaíso",
			"Viña del Mar",
			"Limache",
			"Olmué",
			"Quilpué",
			"Villa Alemana",
		],
	},
	vi: {
		name: "Libertador General Bernardo O'Higgins",
		communes: [
			"Codegua",
			"Coínco",
			"Coltauco",
			"Doñihue",
			"Graneros",
			"Las Cabras",
			"Machalí",
			"Malloa",
			"Mostazal",
			"Olivar",
			"Peumo",
			"Pichidegua",
			"Quinta de Tilcoco",
			"Rancagua",
			"Rengo",
			"Requínoa",
			"San Vicente de Tagua Tagua",
			"La Estrella",
			"Litueche",
			"Marchigüe",
			"Navidad",
			"Peredones",
			"Pichilemu",
			"Chépica",
			"Chimbarongo",
			"Lolol",
			"Nancagua",
			"Palmilla",
			"Peralillo",
			"Placilla",
			"Pumanque",
			"San Fernando",
			"Santa Cruz",
		],
	},
	vii: {
		name: "Maule",
		communes: [
			"Cauquenes",
			"Chanco",
			"Pelluhue",
			"Curicó",
			"Hualañé",
			"Licantén",
			"Molina",
			"Rauco",
			"Romeral",
			"Sagrada Familia",
			"Teno",
			"Vichuquén",
			"Colbún",
			"Linares",
			"Longaví",
			"Parral",
			"Retiro",
			"San Javier de Loncomilla",
			"Villa Alegre",
			"Yerbas Buenas",
			"Constitución",
			"Curepto",
			"Empedrado",
			"Maule",
			"Pelarco",
			"Pencahue",
			"Río Claro",
			"San Clemente",
			"San Rafael",
			"Talca",
		],
	},
	viii: {
		name: "Biobío",
		communes: [
			"Arauco",
			"Cañete",
			"Contulmo",
			"Curanilahue",
			"Lebu",
			"Los Álamos",
			"Tirúa",
			"Alto Biobío",
			"Antuco",
			"Cabrero",
			"Laja",
			"Los Ángeles",
			"Mulchén",
			"Nacimiento",
			"Negrete",
			"Quilaco",
			"Quilleco",
			"San Rosendo",
			"Santa Bárbara",
			"Tucapel",
			"Yumbel",
			"Chiguayante",
			"Concepción",
			"Coronel",
			"Florida",
			"Hualpén",
			"Hualqui",
			"Lota",
			"Penco",
			"San Pedro de la Paz",
			"Santa Juana",
			"Talcahuano",
			"Tomé",
		],
	},
	ix: {
		name: "Araucanía",
		communes: [
			"Carahue",
			"Cholchol",
			"Cunco",
			"Curarrehue",
			"Freire",
			"Galvarino",
			"Gorbea",
			"Lautaro",
			"Loncoche",
			"Melipeuco",
			"Nueva Imperial",
			"Padre las Casas",
			"Perquenco",
			"Pitrufquén",
			"Pucón",
			"Puerto Saavedra",
			"Teodoro Schmidt",
			"Toltén",
			"Vilcún",
			"Villarrica",
			"Angol",
			"Collipulli",
			"Curacautín",
			"Ercilla",
			"Lonquimay",
			"Los Sauces",
			"Lumaco",
			"Purén",
			"Renaico",
			"Traiguén",
			"Victoria",
		],
	},
	x: {
		name: "Los Lagos",
		communes: [
			"Ancud",
			"Castro",
			"Chonchi",
			"Curaco de Vélez",
			"Dalcahue",
			"Puqueldón",
			"Queilén",
			"Quemchi",
			"Quellón",
			"Quinchao",
			"Calbuco",
			"Cochamó",
			"Fresia",
			"Frutillar",
			"Llanquihue",
			"Los Muermos",
			"Maullín",
			"Puerto Montt",
			"Puerto Varas",
			"Osorno",
			"Puerto Octay",
			"Purranque",
			"Puyehue",
			"Río Negro",
			"San Juan de la Costa",
			"San Pablo",
			"Chaitén",
			"Futalelfú",
			"Hualaihué",
			"Palena",
		],
	},
	xi: {
		name: "Aysén del General Carlos Ibáñez del Campo",
		communes: [
			"Cisnes",
			"Guaitecas",
			"Aysén",
			"Cochrane",
			"Ohiggins",
			"Tortel",
			"Coyhaique",
			"Lago Verde",
			"Chile Chico",
			"Río Ibañez",
		],
	},
	xii: {
		name: "Magallanes y Antártica Chilena",
		communes: [
			"Antártica",
			"Cabo de Hornos",
			"Laguna Blanca",
			"Punta Arenas",
			"Río Verde",
			"San Gregorio",
			"Porvenir",
			"Primavera",
			"Timaukel",
			"Natales",
			"Torres del Paine",
		],
	},
	xiii: {
		name: "Metropolitana de Santiago",
		communes: [
			"Alhué",
			"Buin",
			"Calera de Tango",
			"Cerrillos",
			"Cerro Navia",
			"Colina",
			"Conchalí",
			"Curacaví",
			"El Bosque",
			"El Monte",
			"Estación Central",
			"Huechuraba",
			"Independencia",
			"Isla de Maipo",
			"La Cisterna",
			"La Florida",
			"La Granja",
			"La Pintana",
			"La Reina",
			"Lampa",
			"Las Condes",
			"Lo Barnechea",
			"Lo Espejo",
			"Lo Prado",
			"Macul",
			"Maipú",
			"María Pinto",
			"Melipilla",
			"Ñuñoa",
			"Padre Hurtado",
			"Paine",
			"Pedro Aguirre Cerda",
			"Peñaflor",
			"Peñalolén",
			"Pirque",
			"Providencia",
			"Pudahuel",
			"Puente Alto",
			"Quilicura",
			"Quinta Normal",
			"Recoleta",
			"Renca",
			"San Bernardo",
			"San Joaquín",
			"San José de Maipo",
			"San Miguel",
			"San Pedro",
			"San Ramón",
			"Santiago",
			"Talagante",
			"Til Til",
			"Vitacura",
		],
	},
	xiv: {
		name: "Los Ríos",
		communes: [
			"Mariquina",
			"Lanco",
			"Máfil",
			"Valdivia",
			"Corral",
			"Paillaco",
			"Los Lagos",
			"Panguipulli",
			"La Unión",
			"Río Bueno",
			"Lago Ranco",
			"Futrono",
		],
	},
	xv: {
		name: "Arica y Parinacota",
		communes: ["Arica", "Camarones", "General Lagos", "Putre"],
	},
	xvi: {
		name: "Ñuble",
		communes: [
			"Cobquecura",
			"Coelemu",
			"Ninhue",
			"Portezuelo",
			"Quirihue",
			"Ránquil",
			"Trehuaco",
			"Bulnes",
			"Chillán Viejo",
			"Chillán",
			"El Carmen",
			"Pemuco",
			"Pinto",
			"Quillón",
			"San Ignacio",
			"Yungay",
			"Coihueco",
			"Ñiquén",
			"San Carlos",
			"San Fabián",
			"San Nicolás",
		],
	},
}

// Endpoint to get all regions
app.get("/regions", (req, res) => {
	const regions = Object.keys(data).map((id) => ({ id, name: data[id].name }))
	res.json(regions)
})

// Endpoint to get communes by region ID
app.get("/regions/:id", (req, res) => {
	const id = req.params.id.toLowerCase().trim()
	const region = data[id]
	if (region) {
		res.json(region.communes)
	} else {
		res.status(404).json({ error: "Region not found" })
	}
})

// Start the server
app.listen(PORT, () => {
	console.log(`Server is running on port ${PORT}`)
})
